apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
data:
  .dockerconfigjson: ewogICJzdGFja09yY2hlc3RyYXRvciIgOiAic3dhcm0iLAogICJhdXRocyIgOiB7CiAgICAiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIiA6IHsKCiAgICB9CiAgfSwKICAiSHR0cEhlYWRlcnMiIDogewogICAgIlVzZXItQWdlbnQiIDogIkRvY2tlci1DbGllbnQvMTkuMDMuMSAoZGFyd2luKSIKICB9LAogICJjcmVkc1N0b3JlIiA6ICJkZXNrdG9wIgp9Cg==
type: kubernetes.io/dockerconfigjson
