# ------------------- TixChange MySQL Deployment ------------------- #

apiVersion: apps/v1 
kind: Deployment
metadata:
  name: tix-mysql-deploy
  namespace: tixchange-v1
  labels:
    app: tixchange-db
    tier: database
    env: {{ .Values.DeploymentEnv1 }}
spec:
  selector:
    matchLabels:
      app: tixchange-db
      tier: database
      env: {{ .Values.DeploymentEnv1 }}
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tixchange-db
        tier: database
        env: {{ .Values.DeploymentEnv1 }}
      annotations:
        ver: "1.0"
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "tixchange-mysql-conn-svc-1"
      containers:
        - resources:
          env:
            - name: apmenv_introscope_agent_defaultProcessName
              value: apmiaMySQL_UC1
            - name: apmenv_introscope_agent_hostName
              value: node2
            - name: APMENV_AGENTMANAGER_URL_1
              value: "APM_MANAGER_URL_1"
            - name: APMENV_AGENTMANAGER_CREDENTIAL
              value: "APM_MANAGER_CREDENTIAL"
            - name: apmenv_db1_hostName
              value: "tixchange-mysql-conn-svc-1"
          name: apmia-mysql-uc1
          image: srikns/apmiamysql:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.7"
              memory: 700M

        - name: tix-mysql
          image: srikns/tixchange-mysql8:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: CAdemo123
          - name: MYSQL_DATABASE
            value: jtixchange
          - name: MYSQL_USER
            value: tcuser
          - name: MYSQL_PASSWORD
            value: quality
          -  name: Zone
             value: "us-east-1c"
          ports:
            - name: db-port
              containerPort: 3306

      nodeSelector:
        kubernetes.io/hostname: node2
      #nodeSelector:
        #nodeNum: "01"

---


# -------------------  MySQL Service ------------------- #

apiVersion: v1
kind: Service
metadata:
  name: tixchange-mysql-conn-svc-1
  namespace: tixchange-v1
  labels:
    app: tixchange-db
    tier: database
spec:
  selector:
    app: tixchange-db 
    tier: database
  ports:
  - name: mysql-port
    port: 3306
    targetPort: 3306

