apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apmia-asm
  labels:
    tier: monitoring
    app: caagent_apmia_asm
    version: v1
spec:
  template:
    metadata:
      labels:
        app: caagent_apmia_asm
    spec:
      containers:
        - resources:
          env:
            - name: CA_APM_MONITORING_ENABLED
              value: "false"
            - name: APMENV_LOG4J_LOGGER_INTROSCOPEAGENT
              value: INFO,console, logfile
            - name: APMENV_AGENTMANAGER_URL_1
              value: wss://cloudgw.dxi-na1.saas.broadcom.com
            - name:  APMENV_AGENTMANAGER_CREDENTIAL
              value: eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1NiJ9.eyJhZ2VudCI6dHJ1ZSwiZXhwIjo5MjIzMzcyMDM2ODU0Nzc1LCJ0aWQiOjEwNTcsImp0aSI6ImViMjM4MDlkLWUwZWMtNGM2MC1iMjkyLTc1MmE2MTVmNThlMyJ9.dK72nuz8hcgiNxe5g2Fsu9jgNzr-sJH9D3qu0UoDtD-CGz7A7hUqo68f0FDv8_AWV0HnZEpo0u3MM2p3K9fc8w
            - name: APMENV_INTROSCOPE_AGENT_ASM_USEREMAIL
              value: "pindo01@ca.com"
            - name: APMENV_INTROSCOPE_AGENT_ASM_APIPASSWORD
              value: "password2"
            - name: APMENV_INTROSCOPE_AGENT_EXTENSIONS_BUNDLES_BOOT_LOAD
              value: "asm-monitor"
            - name: APMENV_INTROSCOPE_AGENT_AGENTNAME
              value: apmia_asm_agent
            - name: APMENV_INTROSCOPE_AGENT_HOSTNAME
              value: apmia_asm_monitoring
            - name: APMENV_INTROSCOPE_AGENT_AWS_PROFILES_AWS_INTERVAL
              value: "180"
          name: apmia-asm
          image: srikns/ca-asm:latest
          imagePullPolicy: Always
          resources:
           limits:
            cpu: "0.7"
            memory: 700M
