apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tichange-ws-uc2-virt-svc
spec:
  hosts:
  - authservice-svc.tixchange-v2.svc.cluster.local
  http:
  - route:
    - destination:
        host: authservice-svc.tixchange-v2.svc.cluster.local
        subset: version-v2
      weight: 100
---
