apiVersion: apps/v1
kind: Deployment
metadata:
  name: caagent-apmia-aws
  labels:
    tier: monitoring
    app: caagent-apmia-aws
    version: v1
spec:
  selector:
    matchLabels:
      app: caagent-apmia-aws
  template:
    metadata:
      labels:
        app: caagent-apmia-aws
    spec:
      containers:
        - resources:
          env:
            - name: APMENV_LOG4J_LOGGER_INTROSCOPEAGENT
              value: INFO,console, logfile
            - name: APMENV_AGENTMANAGER_URL_1
              value: APM_MANAGER_URL_1
            - name:  APMENV_AGENTMANAGER_CREDENTIAL
              value: APM_MANAGER_CREDENTIAL
            - name: APMENV_INTROSCOPE_AGENT_AWS_PROFILES_AWS_ACCOUNTS
              value: "AWS_ACCOUNTS_NUMBS"
            - name: APMENV_INTROSCOPE_AGENT_EXTENSIONS_BUNDLES_BOOT_LOAD
              value: AWS_BUNDLE_FOLDER
            - name: APMENV_INTROSCOPE_AGENT_AWS_PROFILES_AWS_REGIONLIST
              value: AWS_REGIONS
            - name: APMENV_INTROSCOPE_AGENT_AWS_PROFILES_AWS_SCHEMALIST
              value: AWS_SERVICES
            - name: APMENV_INTROSCOPE_AGENT_AGENTNAME
              value: apmia_aws_agent
            - name: APMENV_INTROSCOPE_AGENT_HOSTNAME
              value: apmia_aws_monitoring
            - name: APMENV_INTROSCOPE_AGENT_AWS_PROFILES_AWS_INTERVAL
              value: "180"
          name: apmia
          image: caapm/apmia:latest
          imagePullPolicy: Always
          resources:
           limits:
            cpu: "2"
            memory: 1G 
           requests:
            cpu: 200m
            memory: 300Mi
