version: "1.0"
configElements:
  - objectName: "java.lang:type=Runtime"
    attribute: "VmName"
    metricName: "{rootNode}|JVM:Vm Name"
    metricType: "string"
  - objectName: "java.lang:type=Runtime"
    attribute: "VmVersion"
    metricName: "{rootNode}|JVM:Vm Version"
    metricType: "string"
  - objectName: "java.lang:type=OperatingSystem"
    attribute: "AvailableProcessors"
    metricName: "{rootNode}|JVM|OS:Processor Count"
    metricType: "counter"
  - objectName: "java.lang:type=OperatingSystem"
    attribute: "Arch"
    metricName: "{rootNode}|JVM|OS:Architecture"
    metricType: "string"
  - objectName: "java.lang:type=OperatingSystem"
    attribute: "Name"
    metricName: "{rootNode}|JVM|OS:Name"
    metricType: "string"
  - objectName: "java.lang:type=Threading"
    attribute: "ThreadCount"
    metricName: "{rootNode}|JVM|{type}:Current Thread Count"
    metricType: "counter"
  - objectName: "java.lang:type=Threading"
    attribute: "ThreadCount"
    metricName: "{rootNode}|JVM|{type}:New Threads Per Interval"
    metricType: "rate"
  - objectName: "java.lang:type=Threading"
    attribute: "PeakThreadCount"
    metricName: "{rootNode}|JVM|{type}:Peak Thread Count"
    metricType: "counter"
  - objectName: "java.lang:type=Threading"
    attribute: "DaemonThreadCount"
    metricName: "{rootNode}|JVM|{type}:Daemon Thread Count"
    metricType: "counter"
  - objectName: "java.lang:type=ClassLoading"
    attribute: "LoadedClassCount"
    metricName: "{rootNode}|JVM|{type}:Loaded Class Count"
    metricType: "counter"
  - objectName: "java.lang:type=ClassLoading"
    attribute: "UnloadedClassCount"
    metricName: "{rootNode}|JVM|{type}:Unloaded Class Count"
    metricType: "counter"
  - objectName: "java.lang:type=ClassLoading"
    attribute: "TotalLoadedClassCount"
    metricName: "{rootNode}|JVM|{type}:Total Loaded Class Count"
    metricType: "counter"
  - objectName: "java.lang:type=GarbageCollector,*"
    attribute: "CollectionCount"
    metricName: "{rootNode}|JVM|GC Monitor|Garbage Collectors|{name}:Collection Count"
    metricType: "counter"
  - objectName: "java.lang:type=GarbageCollector,*"
    attribute: "CollectionTime"
    metricName: "{rootNode}|JVM|GC Monitor|Garbage Collectors|{name}:Collection Time"
    metricType: "counter"
  - objectName: "java.nio:type=BufferPool"
    attribute:  "MemoryUsed"
    metricName: "{rootNode}|JVM|{type}|{name}:Memory Used"
    metricType: "counter"
