{
 "title": "01 Services Overview",
 "tags": [
  "1demo",
  "DX OI Service Details"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "tenant",
    "query": "{\"find\":\"terms\",\"field\":\"tenant_name\"}"
   },
   {
    "name": "Service",
    "query": "{\"find\":\"terms\",\"field\":\"service_name\"}"
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "content": "# Service Overview Dashboard  " },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": {
    "content": "<b><h1 style=\"color: Black; background-color: BlanchedAlmond; font-size: 20px;\"><center>SERVICE</center></h1></b>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Business Service Health",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "additionalParams": {
      "alias": "",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "service_name" ],
      "legendMetricField": "Custom Attribute",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "service_name",
      "aggregationCatergory": "None",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "5000",
      "order": "BOTTOM"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "{\n  \"query\": [\n    {\n      \"op\": \"FROM\",\n      \"querySpecifier\": {\n        \"attributeNameSpecifier\": {\n          \"ignoreCase\": false,\n          \"op\": \"REGEX\",\n          \"pattern\": \".*\\\\:service_health\"\n        },\n        \"op\": \"SPEC\",\n        \"sourceNameSpecifier\": {\n          \"names\": [\n            \"OI|SA|SERVICES|ALL\"\n          ],\n          \"op\": \"EXACT\"\n        }\n      }\n    },\n    {\n      \"op\": \"GROUP\",\n      \"columns\": [\n        \"metric.source\",\n        \"metric.path\"\n      ]\n    },\n    {\n      \"op\": \"AGG\",\n      \"spec\": [\n        {\n          \"op\": \"LAST\",\n          \"column\": \"data.value\",\n          \"as\": \"Service Health\"\n        },\n        {\n          \"op\": \"LAST\",\n          \"column\": \"metric.attr.service_name\",\n          \"as\": \"Service Name\"\n        }\n      ]\n    },\n    {\n      \"op\": \"BOTTOM\",\n      \"column\": \"Service Health\",\n      \"n\": 500\n    },\n    {\n      \"op\": \"KEEP\",\n      \"columns\": [\n        \"Service Name\",\n        \"Service Health\"\n      ]\n    }\n  ]\n}",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "Service Name", "yaxis": [ "Service Health" ] },
      "nassAggregationMode": "Time Series",
      "nassAggregationsEnabled": true
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ".*:service_health"
        },
        {
         "expressions": [
          { "name": "service_name", "operator": "MATCHES", "values": [ "$Service" ] }
         ],
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ATTRIBUTE"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "names": [ "OI|SA|SERVICES|ALL" ],
         "op": "EXACT"
        }
       ]
      }
     ],
     "tenantId": "test1"
    }
   ]
  },
  {
   "title": "What Changed ???",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "datasourceType": "AIOps_Elasticsearch",
     "metrics": [
      {
       "$$hashKey": "object:8214",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 50 },
       "type": "raw_document"
      }
     ],
     "primaryIndex": "ao_itoa_events_change_custom_1",
     "query": "a2n-tix-app-node-2 OR host:TIX-R2",
     "timeField": "@timestamp"
    },
    {
     "datasourceType": "AIOps_Elasticsearch",
     "metrics": [
      {
       "$$hashKey": "object:86",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 50 },
       "type": "raw_document"
      }
     ],
     "primaryIndex": "ao_itoa_events_change_spectrum_1",
     "query": "host:TIX-R2",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Number of Active Users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:48",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "1m", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "datasourceType": "AIOps_Elasticsearch",
     "metrics": [
      {
       "$$hashKey": "object:45",
       "field": "user_id",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "primaryIndex": "ao_axa_session_events_1",
     "query": "user_id:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alarms by Service",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:544",
       "fake": true,
       "field": "service_name",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "500" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:545",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "datasourceType": "AIOps_Elasticsearch",
     "metrics": [
      { "$$hashKey": "object:542", "field": "select field", "id": "1", "type": "count" }
     ],
     "primaryIndex": "ao_itoa_alarms_service_sa_*",
     "primaryMapCol": "service_name",
     "query": "service_name:$Service AND state:ACTIVE",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 20 },
   "options": {
    "content": "<br>\n<p style=\"color:black;background-color: BlanchedAlmond; text-align: right; font-size: 20px;width:49%; display: inline-block;\"><strong>APPLICATION</strong></p><p style=\"color:black;background-color: BlanchedAlmond;font-size: 20px; text-align: right; width:50%;  display: inline-block;\"><strong><a href=\"https://dxi-dashboard.dxi-na1.saas.broadcom.com/d/E8GmrUrWz2aig/1-application-detail?orgId=581&from=now-6h&to=now\" style=\"color: blue\">Application Detail</a></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Response Time (ms)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Average Response Time (ms)" }
   ],
   "targets": [
    {
     "additionalParams": {
      "alias": "",
      "clampSize": "100",
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "None",
      "displayTimeSeries": true,
      "enableAggregation": true,
      "limit": "",
      "order": "TOP",
      "resultFormat": "Time Series"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Frontends\\|Apps\\|[^|]+\\|URLs\\|.*:Average Response Time \\(ms\\)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ".*(TxChangeWeb_UC1|TxChangeWeb_UC2)\\|(.*)\\|(.*)"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Responses Per Interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Average Response Time (ms)" }
   ],
   "targets": [
    {
     "additionalParams": {
      "alias": "",
      "clampSize": "100",
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "None",
      "displayTimeSeries": true,
      "enableAggregation": true,
      "limit": "",
      "order": "TOP",
      "resultFormat": "Time Series"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Frontends\\|Apps\\|[^|]+\\|URLs\\|.*:Responses Per Interval"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ".*(TxChangeWeb_UC2|TxChangeWeb_UC1)\\|(.*)\\|(.*)"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors Per Interval",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 22 },
   "yaxes": [
    { "format": "short", "label": "Average Response Time (ms)" }
   ],
   "targets": [
    {
     "additionalParams": {
      "alias": "",
      "clampSize": "100",
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "None",
      "displayTimeSeries": true,
      "enableAggregation": true,
      "limit": "",
      "order": "TOP",
      "resultFormat": "Time Series"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Frontends\\|Apps\\|[^|]+\\|URLs\\|.*:Errors Per Interval"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ".*(TxChangeWeb_UC1|TxChangeWeb_UC2)\\|(.*)\\|(.*)"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 28 },
   "options": {
    "content": "<b><h1 style=\"color: Black; background-color: BlanchedAlmond; font-size: 20px;\"><center>KUBERNETES</center></h1></b>\n"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Detail Per Namespace",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "additionalParams": {
      "alias": "Total Pods",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Source | Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "{\n  \"query\": [\n    {\n      \"op\": \"FROM\",\n      \"querySpecifier\": {\n        \"op\": \"SPEC\",\n        \"sourceNameSpecifier\": {\n          \"op\": \"REGEX\",\n          \"pattern\": \"SuperDomain\\\\|.*\\\\|ClusterDeployment\\\\|Infrastructure Agent\"\n        },\n        \"attributeNameSpecifier\": {\n          \"op\": \"REGEX\",\n          \"pattern\": \"Openshift\\\\|Projects\\\\|.*:Total ReplicaSets\"\n        },\n        \"clampSize\": 0\n      }\n    },\n    {\n      \"op\": \"GROUP\",\n      \"columns\": [\n        \"metric.source[1]\",\n        \"metric.path[2]\"\n      ]\n    },\n    {\n      \"op\": \"MEAN\",\n      \"column\": \"data.value\"\n    },\n    {\n      \"op\": \"FROM\",\n      \"querySpecifier\": {\n        \"op\": \"SPEC\",\n        \"sourceNameSpecifier\": {\n          \"op\": \"REGEX\",\n          \"pattern\": \"SuperDomain\\\\|.*\\\\|ClusterDeployment\\\\|Infrastructure Agent\"\n        },\n        \"attributeNameSpecifier\": {\n          \"op\": \"REGEX\",\n          \"pattern\": \"Openshift\\\\|Projects\\\\|.*:Total Pods\"\n        },\n        \"clampSize\": 0\n      }\n    },\n    {\n      \"op\": \"GROUP\",\n      \"columns\": [\n        \"metric.source[1]\",\n        \"metric.path[2]\"\n      ]\n    },\n    {\n      \"op\": \"MEAN\",\n      \"column\": \"data.value\"\n    }\n  ]\n}",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ".*\\|Namespaces\\|[^|]+:Total Pods"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "SuperDomain\\|.*\\|ClusterDeployment\\|Infrastructure Agent"
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "Total Restarts",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:Total Restarts"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "Total Running Pods",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:Total Running Pods"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "Total Error Pods",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:Total Error Pods"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "CPU Limit (mCore)",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:CPU Limit \\(mCore\\)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "CPU Request (mCore)",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:CPU Request \\(mCore\\)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "CPU Utilization (mCore)",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:CPU Utilization \\(mCore\\)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "Memory Limit (Bytes)",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:Memory Limit \\(Bytes\\)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "Memory Request (Bytes)",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:Memory Request \\(Bytes\\)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    },
    {
     "additionalParams": {
      "alias": "Memory Usage (Bytes)",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "100",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "Kubernetes\\|Namespaces\\|[^|]+:Memory Usage \\(Bytes\\)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Pods State Per Node",
   "type": "table",
   "description": "Describes State of Each Pod in a Namespace and per Node",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "additionalParams": {
      "alias": "",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "metricPath",
      "displayTimeSeries": false,
      "enableAggregation": true,
      "limit": "",
      "order": "TOP",
      "resultFormat": "Table"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "SuperDomain\\|node3\\|OpenShiftTixCluster\\|Kubernetes Agent\\|Openshift\\|Projects\\|.*\\|Pods|.*\\|Containers\\|.*:Container State"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "bucketAggs": [
      {
       "$$hashKey": "object:62777",
       "field": "timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "datasourceType": "AIops_NASS",
     "metrics": [
      { "$$hashKey": "object:62775", "field": "select field", "id": "1", "type": "count" }
     ],
     "nassAggregations": {
      "aggregationsRawQuery": "{\n   \"query\":[\n      {\n         \"op\":\"FROM\",\n         \"querySpecifier\":{\n            \"op\":\"SPEC\",\n            \"sourceNameSpecifier\":{\n               \"op\":\"REGEX\",\n               \"pattern\":\"SuperDomain\\\\|K8sOpenTracingUMA\\\\|.*\\\\|Kubernetes Agent\"\n            },\n            \"attributeNameSpecifier\":{\n               \"op\":\"REGEX\",\n               \"pattern\":\"Kubernetes\\\\|Namespaces\\\\|.*\\\\|Pods\\\\|(?!.*(cron|complete\\\\-upgrade|install\\\\-calico\\\\-pools)).*:Pod Ready State\"\n            },\n            \"clampSize\":0\n         }\n      },\n      {\n         \"op\":\"GROUP\",\n         \"columns\":[\n            \"metric.source[1]\",\n            \"metric.path[2]\",\n            \"metric.path[4]\"\n         ]\n      },\n      {\n         \"op\":\"MEAN\",\n         \"column\":\"data.value\"\n      }\n   ]\n}",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": true
     },
     "primaryIndex": "ao_itoa_alarms_service_sa_*",
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ]
      }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Kubernetes Events",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "targets": [
    {
     "datasourceType": "AIOps_Elasticsearch",
     "metrics": [
      {
       "$$hashKey": "object:971",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "primaryIndex": "ao_itoa_events_change_custom_1",
     "query": "(host:k8s_jpmc_aiops)",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "<br>\n<p style=\"color:black;background-color: BlanchedAlmond; text-align: right; font-size: 20px;width:49%; display: inline-block;\"><strong>NETWORK</strong></p><p style=\"color:black;background-color: BlanchedAlmond;font-size: 20px; text-align: right; width:50%;  display: inline-block;\"><strong><a href=\"https://dxi-dashboard.dxi-na1.saas.broadcom.com/d/HVMYXMEZk/spectrum-fault-overview-console?orgId=581&refresh=5m\" style=\"color: blue\">Spectrum</a>|<a href=\"https://dxi-dashboard.dxi-na1.saas.broadcom.com/d/78wMUl9Wz/capc-metrics-and-inventory-netops?orgId=581&refresh=5m\" style=\"color: blue\">CAPM</a></strong></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Alarmed Network Entities",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 47 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:148",
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:98",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "datasourceType": "AIOps_Elasticsearch",
     "metrics": [
      {
       "$$hashKey": "object:95",
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "primaryIndex": "ao_itoa_alarms_all_3",
     "primaryMapCol": "host",
     "query": "product:Spectrum",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Alarmed Network Entities over time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:220",
       "fake": true,
       "field": "host",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:221",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 1, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "datasourceType": "AIOps_Elasticsearch",
     "metrics": [
      { "$$hashKey": "object:218", "field": "select field", "id": "1", "type": "count" }
     ],
     "primaryIndex": "ao_itoa_alarms_all_3",
     "primaryMapCol": "host",
     "query": "product:Spectrum",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 55 },
   "options": {
    "content": "<br>\n<p style=\"color:black;background-color: BlanchedAlmond; text-align: right; font-size: 20px;width:49%; display: inline-block;\"><strong>NODE</strong></p><p style=\"color:black;background-color: BlanchedAlmond;font-size: 20px; text-align: right; width:50%;  display: inline-block;\"><strong><a href=\"https://dxi-dashboard.dxi-na1.saas.broadcom.com/d/Yahiep0Zz5NASS1_aig/uim-top-10-devices-by-utilization?orgId=581&refresh=5m\"  style=\"color: blue\">UIM</a></p>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "additionalParams": {
      "alias": "",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "None",
      "displayTimeSeries": true,
      "enableAggregation": true,
      "limit": "",
      "order": "TOP",
      "resultFormat": "Time Series"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "SystemEdge\\|.*\\|CPU:(TotalUtilPercent|TotalIdlePercent)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "(.*)\\|(.*)\\|(.*)"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "additionalParams": {
      "alias": "",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "None",
      "displayTimeSeries": true,
      "enableAggregation": true,
      "limit": "",
      "order": "TOP",
      "resultFormat": "Time Series"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "SystemEdge\\|.*\\|Memory:(MemInUsePercent|SwapInUsePercent)"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "(.*)\\|(.*)\\|(.*)"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Percentage Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 57 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "additionalParams": {
      "alias": "",
      "clampSize": 100,
      "frequency": "auto",
      "legendMetricCustomValues": [ "" ],
      "legendMetricField": "Metric",
      "plotCategories": [ "value" ]
     },
     "aggregations": {
      "aggregateBy": "",
      "aggregationCatergory": "None",
      "displayTimeSeries": true,
      "enableAggregation": true,
      "limit": "",
      "order": "TOP",
      "resultFormat": "Time Series"
     },
     "basicFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": ""
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "isNot": false,
         "logicalOperator": "AND",
         "op": "ALL"
        }
       ]
      }
     ],
     "datasourceType": "AIops_NASS",
     "nassAggregations": {
      "aggregationsRawQuery": "",
      "nassAggModeValues": { "seriesName": [ "" ], "xaxis": "", "yaxis": [ "" ] },
      "nassAggregationMode": "Table",
      "nassAggregationsEnabled": false
     },
     "querytFilters": [
      {
       "attributeNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "SystemEdge\\|.*\\|Storage\\|Disk partition.*:PercentUsed"
        }
       ],
       "isNot": false,
       "logicalOperator": "AND",
       "op": "SPEC",
       "sourceNameSpecifier": [
        {
         "ignoreCase": false,
         "isNot": false,
         "logicalOperator": "AND",
         "op": "REGEX",
         "pattern": "(.*)\\|(.*)\\|(.*)"
        }
       ]
      }
     ]
    }
   ]
  }
 ]
}