apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: srikns/jenkins:latest
        env:
        - name: CA_APM_MONITORING_ENABLED
          value: "false"
        - name: JAVA_OPTS
          value: "-Dhudson.model.DirectoryBrowserSupport.CSP= -Djava.net.preferIPv4Stack=true -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration=false"
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: jenkins-home
            mountPath: /var/jenkins_home
          - name: selenium
            mountPath: /root/selenium
          - name: kube-config
            mountPath: /root/.kube/
          - name: ssh
            mountPath: /root/.ssh/
          - name: open-access
            mountPath: /root/open-access
      volumes:
        - name: kube-config
          hostPath: 
            path: /root/.kube/
            type: Directory 
        - name: jenkins-home
          hostPath: 
            path: /opt/ca/TixChangeK8sDemo/jenkins/jenkins_home
            type: Directory 
        - name: selenium 
          hostPath: 
            path: /opt/ca/TixChangeK8sDemo/selenium/
            type: Directory 
        - name: ssh
          hostPath:
            path: /opt/ca/TixChangeK8sDemo/jenkins/jenkins_ssh
            type: Directory
        - name: open-access
          hostPath:
            path: /opt/ca/TixChangeK8sDemo/open-access
            type: Directory
      nodeSelector:
        kubernetes.io/hostname: node1
---

apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 31080
  selector:
    app: jenkins
