apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: apmia-mysql
  labels:
    tier: monitoring
    app: caagent_apmia
    version: v1

spec:
  template:
    metadata:
      labels:
        app: caagent_apmia
    spec:
      hostAliases:
      - ip: "MY_SQL_SVR_IP"
        hostnames:
        - "tixchange-mysql-conn-svc"
      containers:
        - resources:
          env:
            - name: APMENV_AGENTMANAGER_URL_1
              value: "APM_MANAGER_URL_1"
            - name: APMENV_AGENTMANAGER_CREDENTIAL
              value: "APM_MANAGER_CREDENTIAL"
          name: apmia
          image: srikns/apmiamysql:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.7"
              memory: 700M
