# ------------------- NodeJS  Web App Deployment ------------------- #

apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2. I'm running 1.11.0
kind: Deployment
metadata:
  name: pricing-web-deploy
  namespace: tixchange-v1
  labels:
    app: pricing-web
    tier: frontend
spec:
  selector:
    matchLabels:
      app: pricing-web
      tier: frontend
  replicas: 1
  revisionHistoryLimit: 9 # how many revisions
  strategy:
    rollingUpdate:
      maxSurge: 1 # how many on top of replicas you want
      maxUnavailable: 1 # how many you can afford to be down
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pricing-web
        tier: frontend
        apm: enabled
      annotations:
        ver: "1.0"
    spec:
      containers:
        - name: pricing-web
          env:
          - name: JAEGER_ENDPOINT
            value: http://10.74.121.188:31426/api/traces
            #value: JAEGER_ENDPOINT_URL
          image: srikns/nodejs-opentracing:20.6
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
           limits:
            cpu: "2"
            memory: 1G
           requests:
            cpu: 500m
            memory: 600Mi
          ports:
            - containerPort: 3000
      nodeSelector:
        kubernetes.io/hostname: node2
---

apiVersion: v1
kind: Service
metadata:
  name: pricing-svc
  namespace: tixchange-v1
  labels:
    app: pricing-web
    tier: frontend
spec:
  selector:
    app: pricing-web
    tier: frontend
  ports:
  - port: 3000
    name: pricing-web
    targetPort: 3000

---
