{{- if and (or .Values.agentManager.url .Values.agentManager_url_1) }}
# Probe AutoAttach secrets and config map
{{- if eq .Values.role "team" }}
---
{{ else }}
{{- if or .Values.monitor.application.autoattach.probe.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: caaiops-probe-autoattach-configmap
  namespace: {{ .Release.Namespace }}
data:
  probe-supported-types: nodejs
  nodejs-sidecarconfig.yaml: |
    containers:
    - name: nodejs-probe-autoattach
      image: {{ .Values.imageName }}
      imagePullPolicy: IfNotPresent
      command: ["cp", "-r", "/nodeprobe", "/nodejs-probe/"]
      volumeMounts:
      - name: probe-shared-files
        mountPath: /nodejs-probe
    - name: application-container
      env:
      - name: COLLECTOR_AGENT_HOST
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
      - name: COLLECTOR_AGENT_PORT
        value: "5005"
      - name: CA_APM_PROBENAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      - name: CA_APM_APPNAME
        valueFrom:
          fieldRef:
            fieldPath: metadata.name
      command: ["sh", "-c", "sh /nodejs-probe/nodeprobe/probe-script.sh"]
      volumeMounts:
      - name: probe-shared-files
        mountPath: /nodejs-probe
    volumes:
    - name: probe-shared-files
      emptyDir: {}
---

apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Release.Namespace }}
  name: caaiops-probe-autoattach-certs
data:
  key.pem: |
    LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV3QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktvd2dnU21BZ0VBQW9JQkFRRGZFZXNvTkpoOThDN0oKWFFqcHdVanlSWFdDak9aM0UrZGRFN00xUzFWcm40aWM1QVJmeFE4NVErWDlBOUhpcmtzYzB0S3VBakJuZmkvYQp3YmlMbHU0T3IwaW84SFJiaTZvdDlIQUliNHdEZVNpcHAzOCtxVEdPMlZNWTFRNitVMGpLcnNBa01rbnBwUXJqCkVERUo1ODRNcUlMTVY4TDRERUs5UmIzNUJxRjlPNS9McXdhWlZwcmZiNm84QUwzUFVJelRWc2Y2Z2JJUjZHd2EKaFE3SEhycG1wRnFNYWM5MWtIM1E5ekE1a1pVa2dULzF4M3BQYnBUQTc4c3o4MDRmSGsxS3Y5T2tXbkQ0TGVrKwpReXR1NHZ6cnk2eHpPTm04K3pjSUNUQnVVR3plU2VlcEF4YzVjNm1QZjZ2Vk5LYTJqSzVvd2x2ZFpESFRxNGE3ClB1NmlPQ0JQQWdNQkFBRUNnZ0VCQUtGeEwzY1dzYktiek5DeFE0MGg5VEJhTXRTOE11UEZoUEhwR3c4Y0tZTk4KbjZxa244SE1OZHRsRjZPSlN6SzZuK1FKZEs2NUtOME9CNFpVSThMckJmbWN4SUo0SEU1UkEyWmsvVnd0bHZEQQpsRHhNM0J1MmlnWnZwT05ZOTJXcGt3b1ZkVHY5SlY4eXNuRnBPNFNHdnFxTW5yVlRZdWp3dnJDTE5CVnh4aGlDClgzdFpNeitJa2JvMmxlR094MTdSVUhZNVd5Ny9PS1dVVncwUjcwQzZ2bnIvZWhDZ2twazRqNnlCbUE1bFVnemoKcHZ1c3ZQWVFtNnVpdnc4cjJHK0xGbVlmbXZ1Q1JXN1VsS2NzL01ydGdDWTJLd3AyRXFpVTFLNFlPNCt5WGN1eApyTXlwTXVMeVZrMHFoN3NOeVV6M0VvWlRJNjBCZjRsS01pSEpXcFMvRkZrQ2dZRUE5VjJSbFBMWnhaak9zTkVCCkltdWU5UGVnbkh5SERsSjI4MjJicmRPdTJwL2tueVVoYWpndWE0WTVFcTFNSTRGaXRFSTJha2krTFpuN3N3ZHIKNEtDWXVnNFZkVEF1Q1F5QjNncHZoLytvSkJ0MllhNDJTQzBNcDJYT1c4YjMzTitCZElraldTM0hFcXVLU1N6Ngp6cFZpMVRldmljS2JrR1pRb1lFWXpSWnBwdFVDZ1lFQTZMejQyS28zMlQvZW8xb0QwL3pqSytIUHdhQ1ZucnE1CjMzblNHL0ZUb1B4RGVDY0FzNlJzSHkrUGNScVRKdXBuTzJYL2VqZ25BcVhBRm1vMFl3S3kvUXQyckVRcHVVbzYKUG9LNG9BSDFySzUzL1hNY1RzaDdkNk05Vk55anNNQlAzRGwrdThYRnVTNnA1aXVheGMvNW5ZaDFOVmEvTnZqQQp3RklHSjhZcUJKTUNnWUVBMzlXT0czMDNvUVQzZVdJUlVOOHcwWFNkTm1SN3FGc2VYSStmTjRJbXZ4YWlMM1JsCitVcHJQbmZoMU9IMjFXVVJNRFEvQTlKOGU0ay9qbUMwenVSeXJ6aHQ1c3dmRXU0d0F1a3VPYmpHSUxwVTBtTmsKN1k3N1BqS25nQjRRdTVQQnV4Zm9BVkM3akpLa3dvQ2dCSmxPNGdlOHdVV2hPS2U5NHJlc2NsdUI0a2tDZ1lFQQpyLzA5bXZEVVBIWmNqMTlnNTZzaHlTdis0dWJnWE4vTDc5MzVjR0hESUVmQmFSanRJZXBpVEE2MXhBd1pXK01DClh0c1pIYjFhV2xrbDhJMHN3ZlhualF0ZkdKS09qbXMvc2NjOWZ0a2NnaENIOFdKYTlJUUxRUU55UERwL21RZEQKSEQ5cHd1bWhRdyt6TDdhbldZK1RySGprVUlvaEc1dHNmY0ZJb0VqcnV2c0NnWUVBeUJZbWNRNWxPeEdwU1pCeApBWXNOS1pLcG9mT3J6YU9YMytKcGJ2ZjlkVTlJVXBCbmprZjNjeDA5RXZoM0lOSFFiMzFUbWIydlU0a2tHR3FQCnBaU0pCa3kveHAyUXV3RzdTMTc1TEkzanVLcURDRkNhWkMyNUNXaWc0THBpQkhFMk1EZ0kxVFl0VGYwV0hJaU4KRnVrZStZT0RYVkNXOGJHL1ZWSnJUM0FIUE1BPQotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg==
  cert.pem: |
    LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURxakNDQXBLZ0F3SUJBZ0lKQU1kNC9nd09YYnp6TUEwR0NTcUdTSWIzRFFFQkN3VUFNRjR4Q3pBSkJnTlYKQkFZVEFrbE9NUkV3RHdZRFZRUUtEQWhDY205aFpHTnZiVEVQTUEwR0ExVUVDd3dHUTBFZ1FWQk5NU3N3S1FZRApWUVFERENKaGNHMHRjSEp2WW1VdFlYVjBiMkYwZEdGamFDMXpkbU11WTJGaGNHMHVjM1pqTUI0WERUSXhNRE16Ck1UQTNNak14TjFvWERUSTBNREV4T1RBM01qTXhOMW93WGpFTE1Ba0dBMVVFQmhNQ1NVNHhFVEFQQmdOVkJBb00KQ0VKeWIyRmtZMjl0TVE4d0RRWURWUVFMREFaRFFTQkJVRTB4S3pBcEJnTlZCQU1NSW1Gd2JTMXdjbTlpWlMxaApkWFJ2WVhSMFlXTm9MWE4yWXk1allXRndiUzV6ZG1Nd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3CmdnRUtBb0lCQVFEZkVlc29OSmg5OEM3SlhRanB3VWp5UlhXQ2pPWjNFK2RkRTdNMVMxVnJuNGljNUFSZnhRODUKUStYOUE5SGlya3NjMHRLdUFqQm5maS9hd2JpTGx1NE9yMGlvOEhSYmk2b3Q5SEFJYjR3RGVTaXBwMzgrcVRHTwoyVk1ZMVE2K1Uwaktyc0FrTWtucHBRcmpFREVKNTg0TXFJTE1WOEw0REVLOVJiMzVCcUY5TzUvTHF3YVpWcHJmCmI2bzhBTDNQVUl6VFZzZjZnYklSNkd3YWhRN0hIcnBtcEZxTWFjOTFrSDNROXpBNWtaVWtnVC8xeDNwUGJwVEEKNzhzejgwNGZIazFLdjlPa1duRDRMZWsrUXl0dTR2enJ5Nnh6T05tOCt6Y0lDVEJ1VUd6ZVNlZXBBeGM1YzZtUApmNnZWTkthMmpLNW93bHZkWkRIVHE0YTdQdTZpT0NCUEFnTUJBQUdqYXpCcE1HY0dBMVVkRVFSZ01GNkNHR0Z3CmJTMXdjbTlpWlMxaGRYUnZZWFIwWVdOb0xYTjJZNEllWVhCdExYQnliMkpsTFdGMWRHOWhkSFJoWTJndGMzWmoKTG1OaFlYQnRnaUpoY0cwdGNISnZZbVV0WVhWMGIyRjBkR0ZqYUMxemRtTXVZMkZoY0cwdWMzWmpNQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFBRkVvRHYvbnVTZnpQTE1mczNDZEZ4YytDUFZzelRHSk85WGZzZ1ptb2tGWVdSCjhoRTZWVC9raHNpb2hra2ZNOVNodTNlb3UyWkZzZk12N3hEbmZZYWFudEdTenA2VG0rTzc2ZzlWY1I4YXNZU3QKME9pdThxc1draWJaNmtYVmUyWWhqUk9jakZqalJZeVpFWGN0UFJsTkZudkxaNlUrRFIyd2lXMUFYcEQ1elpiMQpuTUdiRVRYQ1RBMlhjWkxWSzZ2OEhnVTlhMjQzUzJSUFRWdUJEdzRreUpmcW1nUkw5U2RTMFhBWlBQcHJDZEtKCnFOZXhKNFZETENMZGRubXJ4OVZNaVFWU3pnZFoxL3ZDREd1NE9Zdjk2UzNzZG9qMjJDcVJjVFMyN3J2MER2TUIKSzVQb0lNMzJkdHlYZTE3Q296c3A2ekh2QUNUcThOR01iakpKeDF6aQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

{{ end }}
{{ end }}
{{ end }}