{{- if or .Values.agentManager.url .Values.agentManager_url_1 }}
# Common comfig map needed for All extensions
apiVersion: v1
kind: ConfigMap
metadata:
  name: caaiops-config-common
  namespace: {{ .Release.Namespace }}
data:
  cluster_name: "{{ .Values.clusterName }}"
  agentManager_url_1: "{{ or .Values.agentManager.url .Values.agentManager_url_1 }}"
  agentManager_credential: "{{ or .Values.agentManager.credential .Values.agentManager_credential }}"
  agentManager_version: "{{ .Values.agentManager.version | default "" }}"
  agentManager_httpProxy_host: "{{ .Values.agentManager.httpProxy.host }}"
  agentManager_httpProxy_port: "{{ .Values.agentManager.httpProxy.port }}"
  agentManager_httpProxy_username: "{{ .Values.agentManager.httpProxy.username }}"
  agentManager_httpProxy_password: "{{ .Values.agentManager.httpProxy.password }}"
  prometheus_server_url: "{{ .Values.monitor.container.prometheus.backend.endPoint.url }}"
  prometheus_server_username: "{{ .Values.monitor.container.prometheus.backend.endPoint.username }}"
  prometheus_server_password: "{{ .Values.monitor.container.prometheus.backend.endPoint.password }}"
  prometheus_server_token: "{{ .Values.monitor.container.prometheus.backend.endPoint.token }}"
  {{- if or .Values.agentNaming.deployment.apmia.process  }}
  agentNaming_deployment_apmia_process: "{{ .Values.agentNaming.deployment.apmia.process }}"
  {{- else }}
  agentNaming_deployment_apmia_process: "ClusterDeployment"
  {{- end }}
  {{- if or .Values.agentNaming.deployment.apmia.agent  }}
  agentNaming_deployment_apmia_agent: "{{ .Values.agentNaming.deployment.apmia.agent }}"
  {{- else }}
  agentNaming_deployment_apmia_agent: "Infrastructure Agent"
  {{- end }}
  {{- if or .Values.agentNaming.deployment.prometheus.process }}
  agentNaming_deployment_prometheus_process: "{{ .Values.agentNaming.deployment.prometheus.process }}"
  {{- else }}
  agentNaming_deployment_prometheus_process: "ClusterPerformanceMonitor"
  {{- end }}
  {{- if or .Values.agentNaming.deployment.prometheus.agent  }}
  agentNaming_deployment_prometheus_agent: "{{ .Values.agentNaming.deployment.prometheus.agent }}"
  {{- else }}
  agentNaming_deployment_prometheus_agent: "Prometheus Agent"
  {{- end }}
  agentNaming_daemonset_apmia_host: "{{ .Values.agentNaming.daemonset.apmia.host }}"
  {{- if or .Values.agentNaming.daemonset.apmia.agent  }}
  agentNaming_daemonset_apmia_agent: "{{ .Values.agentNaming.daemonset.apmia.agent }}"
  {{- else }}
  agentNaming_daemonset_apmia_agent: "Kubernetes Agent"
  {{- end }}
  opentracing_grpc_hostport: "{{ .Values.monitor.application.opentracing.grpc.hostport }}"
  zipkinTracing_zipkinServer_hostport: "{{ .Values.monitor.application.zipkinTracing.zipkinServer.hostport }}"
  agentNaming_deployment_aws_host: "{{ or .Values.agentNaming.deployment.aws.host }}"
  agentNaming_deployment_aws_process: "{{ or .Values.agentNaming.deployment.aws.process }}"
  agentNaming_deployment_aws_agent: "{{ or .Values.agentNaming.deployment.aws.agent }}"

{{ end }}
