{{- if or .Values.agentManager.url .Values.agentManager_url_1 }}
  # Cluster Discovery Service
{{- if or .Values.k8slegacy }}
apiVersion: apps/v1beta1
{{ else }}
apiVersion: apps/v1
{{ end }}
kind: Deployment
metadata:
  name: clusterinfo
  namespace: {{ .Release.Namespace }}
  labels:
    app: cagent
    module: clusterinfo
  annotations:
    ca.broadcom.application.name: kubernete-cluster-monitoring

spec:
  replicas: 1
  template:
    metadata:
      name: clusterinfo
      labels:
        app: cagent
        module: clusterinfo
    spec:
      serviceAccountName: uma
      containers:
      - name: clusterinfo
        image:  {{ or .Values.imageName .Values.image }}
        env:
{{- if or .Values.k8slegacy }}
          - name: KUBERNETES_LEGACY_VERSION
            value: "true"
{{ end }}
          - name: type
            value: {{ .Values.type }}
{{- if .Values.namespaces }}
          - name: KUBERNETES_NAMESPACE_MONITOR_LIST
            value: "{{ .Values.namespaces }}"
{{ end }}
          - name: cluster_name
            valueFrom:
              configMapKeyRef:
                key: cluster_name
                name: caaiops-config-common
{{- if .Values.EnableResourceLimits }}
        resources:
          limits:
            cpu: 2
            memory: 1G
          requests:
            cpu: 200m
            memory: 300Mi
{{end}}
        imagePullPolicy: Always
        command: ["/usr/local/openshift/apmia/jre/bin/java", "-Xms64m","-Xmx512m", "-jar", "/clusterinfo-1.0.jar"]
        # Comment out this section in case you want to enable debug
        # command: ["java", "-jar", "-Dlogging.level.com.ca.apm.broadcom.kubernetes.springboot.ClusterInfoController=DEBUG","/clusterinfo-1.0.jar"]
      restartPolicy: Always

  selector:
    matchLabels:
      module: clusterinfo
{{ end }}
