{{- if or .Values.agentManager.url .Values.agentManager_url_1 }}
  # Cluster Discovery Service
{{- if eq .Values.role "team" }}
---
{{ else }}
{{- if or .Values.k8slegacy }}
apiVersion: apps/v1beta1
{{ else }}
apiVersion: apps/v1
{{ end }}
kind: Deployment
metadata:
  name: clusterinfo
  namespace: {{ .Release.Namespace }}
  labels:
    app: cagent
    module: clusterinfo
  annotations:
    ca.broadcom.application.name: kubernete-cluster-monitoring

spec:
  replicas: 1
  template:
    metadata:
      name: clusterinfo
      labels:
        app: cagent
        module: clusterinfo
    spec:
      serviceAccountName: uma
      containers:
      - name: clusterinfo
        image:  {{ or .Values.imageName .Values.image }}
        env:
{{- if or .Values.k8slegacy }}
          - name: KUBERNETES_LEGACY_VERSION
            value: "true"
{{ end }}
          - name: type
            value: {{ .Values.type }}
{{- if .Values.namespaces }}
          - name: KUBERNETES_NAMESPACE_MONITOR_LIST
            value: "{{ .Values.namespaces }}"
{{ end }}
          - name: agent_connection_compatibility_version
            valueFrom:
              configMapKeyRef:
                key: agentManager_version
{{- if eq .Values.role "common" }}
                name: caaiops-config-common
{{- else }}
                name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
{{- end }}

          - name: cluster_name
            valueFrom:
              configMapKeyRef:
                key: cluster_name
{{- if eq .Values.role "common" }}
                name: caaiops-config-common
{{- else }}
                name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
{{- end }}
{{- if .Values.EnableResourceLimits }}
        resources:
          limits:
            cpu: 2
            memory: 1.5G
          requests:
            cpu: 400m
            memory: 700Mi
{{end}}
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /up
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 120

{{- if or .Values.isAcc }}
        command: ["/opt/uma/jre/bin/java", "-Xms256m","-Xmx1024m", "-Dlogging.config=file:/opt/uma/utility/logback.xml", "-jar", "/opt/uma/utility/clusterinfo-1.0.jar"]
{{ else }}
        command: ["/usr/local/openshift/apmia/jre/bin/java", "-Xms256m","-Xmx1024m", "-Dlogging.config=file:/usr/local/openshift/logback.xml", "-jar", "/clusterinfo-1.0.jar"]
{{ end }}

        # Comment out this section in case you want to enable debug
        # command: ["java", "-jar", "-Dlogging.level.com.ca.apm.broadcom.kubernetes.springboot.ClusterInfoController=DEBUG","/clusterinfo-1.0.jar"]
      restartPolicy: Always

  selector:
    matchLabels:
      module: clusterinfo
{{ end }}
{{ end }}
