{{- if or .Values.monitor.container.dockerstats.enabled .Values.kubernetes_monitor_enabled }}
#  ( and .Values.monitor.container.prometheus.backend.endPoint.url .Values.agentManager.url )
# APMIA based Deployment.
# Agent from Container1 will be reported to <Cluster_Name>|ClusterMonitoring|Infrastructure Agent

{{- if or .Values.k8slegacy }}
apiVersion: apps/v1beta1
{{ else }}
apiVersion: apps/v1
{{ end }}
kind: Deployment
metadata:
  name: container-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: apmia-deployment
spec:
  replicas: 1
  template:
    metadata:
      name: apmia-deployment
      labels:
        app: apmia-deployment
        deployment.name: container-monitor
    spec:
      serviceAccountName: uma
      initContainers:
      - name: init-clusterinfo
        image: {{ .Values.imageName }}
        command: ['bash', '-c', 'until [ $(curl --connect-timeout 5 --max-time 10 --write-out %{http_code} --silent --output /dev/null ${CLUSTERINFO_SERVICE_HOST}:${CLUSTERINFO_SERVICE_PORT}/up) -eq 200 ]; do sleep 2; done']
      containers:
      - env:
        - name: agentManager_url_1
          valueFrom:
            configMapKeyRef:
              key: agentManager_url_1
              name: caaiops-config-common
{{- if or .Values.agentManager.credential .Values.agentManager_credential }}
        - name: agentManager_credential
          valueFrom:
            configMapKeyRef:
              key: agentManager_credential
              name: caaiops-config-common
{{ end }}
{{- if .Values.agentManager.httpProxy.host }}
        - name: apmenv_agentManager_httpProxy_host
          valueFrom:
            configMapKeyRef:
              key: agentManager_httpProxy_host
              name: caaiops-config-common
{{ end }}
{{- if.Values.agentManager.httpProxy.port }}
        - name: apmenv_agentManager_httpProxy_port
          valueFrom:
            configMapKeyRef:
              key: agentManager_httpProxy_port
              name: caaiops-config-common
{{ end }}
{{- if .Values.agentManager.httpProxy.username }}
        - name: apmenv_agentManager_httpProxy_username
          valueFrom:
            configMapKeyRef:
              key: agentManager_httpProxy_username
              name: caaiops-config-common
{{ end }}
{{- if .Values.agentManager.httpProxy.password }}
        - name: apmenv_agentManager_httpProxy_password
          valueFrom:
            configMapKeyRef:
              key: agentManager_httpProxy_password
              name: caaiops-config-common
{{ end }}

{{- if .Values.namespaces }}
        - name: KUBERNETES_NAMESPACE_MONITOR_LIST
          value: "{{ .Values.namespaces }}"
{{ end }}
        - name: apmenv_introscope_agent_connection_compatibility_version
          valueFrom:
            configMapKeyRef:
              key: agentManager_version
              name: caaiops-config-common
        - name: interval
          value: "120"
        - name: KUEBRNETES_CLUSTER_MONITORING
          value: "true"
        - name: apmenv_introscope_epagent_config_httpServerPort
          value: "8888"
        - name: REDUCE_METRIC_EXPLOSION
          value: {{ if .Values.agentManager.version }} "true" {{ else }} "false" {{ end }}
        - name: type
          value: {{ .Values.type | default "Kubernetes" | quote }}
        - name: HostMonitoring
          value: disabled
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_cluster
          value: {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_cluster_clustername)
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_node
          value: {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_node_clustername), {{ .Values.prefix }}_pod_nodename=(name), {{ .Values.prefix }}_node_agentpath=(agent)
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_namespace
          value: {{ .Values.prefix }}_project=(name), {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_namespace_clustername)
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_pod
          value: {{ .Values.prefix }}_pod_name=(name), {{ .Values.prefix }}_project=({{ .Values.prefix }}_pod_namespace), {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_pod_clustername)
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_deployment
          value: {{ .Values.prefix }}_project=({{ .Values.prefix }}_deployment_namespace), {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_deployment_clustername)
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_daemonset
          value: {{ .Values.prefix }}_project=({{ .Values.prefix }}_daemonset_namespace), {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_daemonset_clustername)
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_container
          value: {{ .Values.prefix }}_pod_nodename=({{ .Values.prefix }}_container_nodename), {{ .Values.prefix }}_pod_container_name=(name), {{ .Values.prefix }}_pod_name=({{ .Values.prefix }}_container_podname),{{ .Values.prefix }}_project=({{ .Values.prefix }}_container_namespace),{{ .Values.prefix }}_pod_container_id=({{ .Values.prefix }}_container_id),  {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_container_clustername)
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_replicaset
          value: {{ .Values.prefix }}_project=({{ .Values.prefix }}_replicaset_namespace),  {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_replicaset_clustername)
        - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_service
          value: {{ .Values.prefix }}_project=({{ .Values.prefix }}_service_namespace),  {{ .Values.prefix }}_cluster_name=({{ .Values.prefix }}_service_clustername)
        - name: apmenv_cluster_name
          valueFrom:
            configMapKeyRef:
              key: cluster_name
              name: caaiops-config-common

        - name: apmenv_introscope_agent_customProcessName
          valueFrom:
            configMapKeyRef:
              key: agentNaming_deployment_apmia_process
              name: caaiops-config-common
        - name: apmenv_introscope_agent_hostName
          valueFrom:
            configMapKeyRef:
              key: cluster_name
              name: caaiops-config-common

        - name: apmenv_introscope_agent_agentName
          valueFrom:
            configMapKeyRef:
              key: agentNaming_deployment_apmia_agent
              name: caaiops-config-common
        - name: apmenv_introscope_agent_extensions_bundles_load
          value: {{- if or .Values.monitor.application.opentracing.enabled }} OpenTracing, {{end}} {{- if or .Values.monitor.container.dockerstats.enabled .Values.kubernetes_monitor_enabled }} {{ if .Values.agentManager.version }} OpenshiftMonitor, {{ else }} ClusterDataReporter, {{ end }} {{ end }}
        - name: MIN_HEAP_VAL_IN_MB
          value: "64"
        - name: cluster_name
          valueFrom:
            configMapKeyRef:
              key: cluster_name
              name: caaiops-config-common


{{- if or .Values.namespaces }}
        - name: apmenv_com_ca_apm_kubernetes_monitor_namespace_list
          value: {{ quote .Values.namespaces }}
{{ end }}
{{- if or .Values.monitor.application.opentracing.enabled }}
        - name: apmenv_introscope_agent_opentracing_grpc_server_hostport
          valueFrom:
            configMapKeyRef:
              key: opentracing_grpc_hostport
              name: caaiops-config-common
{{ end }}
        name: {{ .Chart.Name }}
        image:  {{ or .Values.imageName .Values.image }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8888
          initialDelaySeconds: 60
          periodSeconds: 60
  {{- if or .Values.EnableResourceLimits .Values.kubernetes_resource_bound }}
        resources:
          limits:
            cpu: 2
            memory: 1G
          requests:
            cpu: 200m
            memory: 300Mi
  {{end}}
        imagePullPolicy: Always
      restartPolicy: Always
  selector:
    matchLabels:
      app: apmia-deployment
---
apiVersion: v1
kind: Service
metadata:
  name: opentracing
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: apmia-deployment
  ports:
  - nodePort: 31313
    port: 8888
    protocol: TCP
    targetPort: 8888
  type: LoadBalancer
{{end}}
