apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: broadcom-uma-clusterrole
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/stats
  - nodes/metrics
  - nodes/proxy
  - services
  - pods
  - events
  - pods/exec
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - create
  - list
  - watch
  - patch
- apiGroups:
  - apps
  - admissionregistration.k8s.io
  resources:
  - deployments
  - replicasets
  - daemonsets
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - create
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ca.broadcom.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - anyuid
    - privileged
  verbs:
  - use
- apiGroups:
    - extensions
  resources:
    - podsecuritypolicies
  resourceNames:
    - ibm-privileged-psp
  verbs:
    - use
- apiGroups:
    - apps.openshift.io
  resources:
    - deploymentconfigs
  verbs:
    - get
    - list
    - watch
    - create
    - patch