apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: uma-cluster-role
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - pods
  - pods/exec
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - namespaces
  - persistentvolumes
  - persistentvolumeclaims
  verbs:
  - get
  - create
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
- apiGroups:
  - extensions
  resources:
  - deployments
  - replicasets
  - daemonsets
  verbs:
  - get
  - list
  - watch
  - create
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ca.broadcom.com
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - anyuid
    - privileged
  verbs:
  - use
