{{- if and (or .Values.agentManager.url .Values.agentManager_url_1) }}
{{- if eq .Values.role "team" }}
{{- if or .Values.monitor.node.enabled}}


# Source: uma/templates/daemonset_apmia.yaml

# DaemonSet Configuration
# Agent from Container1 will be reported to <Node_Name>|Infrastructure|Agent
# Agent from Container2 will be reported to <Node_Name>|Application|JMX Agent
{{- if or .Values.k8slegacy }}
apiVersion: apps/v1beta1
{{ else }}
apiVersion: apps/v1
{{ end }}
kind: Deployment
metadata:
  name: broadcom-monitor-host{{- .Values.id | default "1" }}
  namespace: {{ .Release.Namespace }}
  labels:
    tier: monitoring
    app: cagent


spec:
  # oc adm policy add-scc-to-user privileged -z default
  selector:
    matchLabels:
      app: broadcom-monitor-agent
  template:
    metadata:
      labels:
        app: broadcom-monitor-agent
      annotations:
        ca.broadcom.application.name: container-monitoring
    spec:
      containers:
        - env:
            - name: containerflow
              value: disabled
            - name: agentManager_url_1
              valueFrom:
                configMapKeyRef:
                  key: agentManager_url_1
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: agentManager_credential
              valueFrom:
                configMapKeyRef:
                  key: agentManager_credential
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}

            - name: apmenv_introscope_agent_connection_compatibility_version
              valueFrom:
                configMapKeyRef:
                  key: agentManager_version
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: type
              value: Kubernetes
            - name: interval
              value: "60"
            - name: apmenv_introscope_agent_extensions_bundles_load
              value:  HostMonitor
            - name: HostMonitoring
              value: disabled
            - name: KUEBRNETES_NODE_MONITORING
              value: "true"
            - name: DOCKER_STATS_CGROUP_MODE
              value: enabled
            - name: CLUSTERINFO_SERVICE_HOST
              value: {{ .Values.clusterinfo.service | default "clusterinfo.broadcom-aiops.svc.cluster.local" | quote }}
            - name: CLUSTERINFO_SERVICE_PORT
              value: {{ .Values.clusterinfo.port | default "8080" | quote }}
{{- if .Values.agentManager.version }}
            - name: KUEBRNETES_CLUSTER_MONITORING
              value: "true"
{{ end }}
            - name: apmenv_com_ca_apm_kubernetes_remote_monitor_type
              value: jmx,
            - name: apmenv_introscope_agent_remotejmx_clamp
              value: "5000"
            - name: apmenv_introscope_agent_hostmonitor_remote_monitor
              value: "true"
            - name: apmenv_introscope_agent_hostmonitor_remote_monitor_namespace
              valueFrom:
                configMapKeyRef:
                  key: monitored_namespace_list
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: nodename
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: apmenv_com_ca_apm_kubernetes_clusterName
              valueFrom:
                configMapKeyRef:
                  key: cluster_name
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: apmenv_introscope_epagent_config_httpServerPort
              value: "8888"
            - name: REDUCE_METRIC_EXPLOSION
              value: "false"
            - name: apmenv_com_ca_apm_kubernetes_monitor_legacy
              value:  "false"
            - name: KUBERNETES_NAMESPACE_MONITOR_LIST
              valueFrom:
                configMapKeyRef:
                  key: monitored_namespace_list
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_cluster
              value: k8s_cluster_name=(k8s_cluster_clustername)
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_node
              value: k8s_cluster_name=(k8s_node_clustername),k8s_pod_nodename=(name),k8s_node_agentpath=(agent),Hostname=(name),ipAddress=(k8s_node_InternalIP)
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_namespace
              value: k8s_project=(name), k8s_cluster_name=(k8s_namespace_clustername)
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_pod
              value: k8s_pod_name=(name), k8s_project=(k8s_pod_namespace), k8s_cluster_name=(k8s_pod_clustername)
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_deployment
              value: k8s_project=(k8s_deployment_namespace), k8s_cluster_name=(k8s_deployment_clustername)
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_daemonset
              value: k8s_project=(k8s_daemonset_namespace), k8s_cluster_name=(k8s_daemonset_clustername)
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_container
              value: k8s_pod_nodename=(k8s_container_nodename), k8s_pod_container_name=(name), k8s_pod_name=(k8s_container_podname),k8s_project=(k8s_container_namespace),k8s_pod_container_id=(k8s_container_id),  k8s_cluster_name=(k8s_container_clustername)
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_replicaset
              value: k8s_project=(k8s_replicaset_namespace),  k8s_cluster_name=(k8s_replicaset_clustername)
            - name: apmenv_com_ca_apm_clusterdatareporter_additional_attributes_service
              value: k8s_project=(k8s_service_namespace),  k8s_cluster_name=(k8s_service_clustername)
            - name: AIOPS_INSTALL_ROLE
              value: "team"
            - name: apmenv_cluster_name
              valueFrom:
                configMapKeyRef:
                  key: cluster_name
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}

            - name: apmenv_introscope_agent_customProcessName
              value: HostMonitor
            - name: apmenv_introscope_agent_hostName
              valueFrom:
                configMapKeyRef:
                  key: cluster_name
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}

            - name: apmenv_introscope_agent_agentName
              valueFrom:
                configMapKeyRef:
                  key: agentNaming_deployment_apmia_agent
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: MIN_HEAP_VAL_IN_MB
              value: "64"
            - name: cluster_name
              valueFrom:
                configMapKeyRef:
                  key: cluster_name
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: apmenv_com_ca_apm_kubernetes_monitor_namespace_list
              valueFrom:
                configMapKeyRef:
                  key: monitored_namespace_list
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: apmenv_introscope_agent_opentracing_grpc_server_hostport
              valueFrom:
                configMapKeyRef:
                  key: opentracing_grpc_hostport
                  name: caaiops-config-{{- .Values.role | default "common" }}{{- .Values.id | default "1" }}
            - name: apmenv_introscope_agent_hostmonitor_profiles_localhost_linux_groups
              value: memory,cpu,network,diskio,hostresources,application,protocol,systemmanagement,performance,process,ipc,distributedsystem,topprocess,operatingsystem,storage,systemload,port
          name: podmonitor
          image: {{ .Values.imageName }}
          resources:
            limits:
              cpu: 2
              memory: 1G
            requests:
              cpu: 200m
              memory: 300Mi

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8888
            initialDelaySeconds: 60
            periodSeconds: 60

          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /usr/local/openshift/apmia/extensions/HostMonitor/config
      volumes:
        - name: config-volume
          configMap:
            name: caaiops-config-host{{- .Values.id | default "1" }}


{{- end }}
{{- end }}
{{- end }}
